"""01_initial-db

Revision ID: 74463d7e98f7
Revises: 
Create Date: 2023-03-19 11:14:43.951356

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74463d7e98f7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("id", sa.String(length=12), nullable=False),
        sa.Column("original_url", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_link_created_at"), "link", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_link_created_at"), table_name="link")
    op.drop_table("link")
    # ### end Alembic commands ###
