"""03_add_link_deleted_status

Revision ID: 812eae4d9710
Revises: 53e656d1b92d
Create Date: 2023-03-23 22:52:32.123480

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "812eae4d9710"
down_revision = "53e656d1b92d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("link", sa.Column("deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link", "deleted")
    # ### end Alembic commands ###
